name: Build-arm64

on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    name: Build-arm64 
    steps:
      - uses: actions/checkout@v2
      - uses: darsvador/run-on-arch-action@v1.0.10
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          run: |
            export DEBIAN_FRONTEND=noninteractive 
            apt update
            apt install -y build-essential cmake libgl1-mesa-dev libsdl2-dev libvulkan-dev git clang
            git clone --recursive https://github.com/hrydgard/ppsspp.git && cd ppsspp
            mkdir ppsspp && cd ppsspp
            cmake -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchains/raspberry.armv8.cmake ..
            make -j4 && zip -r ppsspp.zip ppsspp/
            curl --upload-file ppsspp.zip https://transfer.sh/
            

            
